//Dado let palabras = ["banana", "manzana", "pera", "uva"], usa .sort() para ordenarlas alfabéticamente.

//DEFINIMOS EL ARREGLO DE PALABRAS CON LOS ELEMENTOS DESORDENADOS
let palabras = ["manzana", "uva", "banana", "pera"];

//USAMOS EL MÉTODO .sort() PARA ORDENAR EL ARREGLO ALFABÉTICAMENTE.
//ESTE MÉTODO TAMBIEN PUEDE USARSE PARA ORDENAR NÚMEROS EN VALOR ASCENDENTE.
palabras.sort();

//IMPRIMIMOS EL ARREGLO ORDENADO
console.log(palabras);